logging:
  level:
    root: info
    win.doyto.query: debug

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
